const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || ".",
    ownerName: process.env.OWNER_NAME || "Toxxic-Boy",
    ownerNumber: process.env.OWNER_NUMBER || "2349063026887",
    mode: process.env.MODE || "public",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "true",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "true",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0ZyQUNiRUkwdGx5WjIzNWtMZXZhRnhWU0NuOVF2S0szamlJWnZLWmZXRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUG9ZRDlUTkNIQ2RwN0lCOFk1SFJ4akJ0YnZvUGM0aldrVVg1OHZ4Sm1oWT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJrSEM5RldRMkVSSkhvMWRoYUx3L01LdjZyNlBFS1gxZjQ1WThYSVZ3alhzPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJGcFFzRWRmaE5neXowcjQyWUkzeld6c0Y5dlJNOTFsbE9mVklsNFJiNUFvPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InNBK1JUbkJFc2d3TUVWZmJOQXVlbUZGeWt5SmZVUHYySkpKMEppUXFQVzQ9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InE3WVNORjdGaTZaSmgzcWJnZTRmdXdKVFFPK2hOVkN1cXNHa0JPT1pQMUk9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0RzZnBDR2pVcHV1dURma2JIbkZQTEVCTFd5QUZycWtIb0hOdzdVSWVtaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieG5UYUNFQjV4d0xNeUEvS3hPQWtpOHBYdUNsOUh2bnd4aVNpeCtnZUVqdz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ijl0ZmFaekNDeHpNaHg2SFVubTJGYktmRmlKSmdMTy9wK0RmckdxendlaTl4bWE4dUJwR1RsNmd4UnNRL05RUUVzYnBVYmxRZlBJL2paVmlHYVB2UmlBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTcwLCJhZHZTZWNyZXRLZXkiOiIvUUYzVE1uUW1wcW52STFxK2w1RlcvZHZVclJ3NVVyS05Ia2VaSi9YQnN3PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJKMTNISE5TOCIsIm1lIjp7ImlkIjoiMjM0OTA2MzAyNjg4NzoxOUBzLndoYXRzYXBwLm5ldCIsImxpZCI6Ijc2Mzk1MDg2NjcyMDczOjE5QGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUExpakpjQkVJYnA1NzBHR0FNZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiVjNTMlU5aTFQanRFck9XbDM1eTh4UFRhcHFoa09BSXk1dUdOVENDOVRsYz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiMm5KYVczc2g3K0RZUVFGajB4Wnp4QThTak52RWcyUXpudDZvc3VOQXZwT0h4SnAzcHFwZXFnanR1dXk5RldFQzdRaGlrUVZGSFBDQmdOUThrZFJGRHc9PSIsImRldmljZVNpZ25hdHVyZSI6IjVZUGp6aktNbE1zcmExcWJMbUlQZkhvbFJrRTArUHVVNmNpOHpnTzVweFFxaW81SWdSOThiQ29WZXVMc0xFT3pLdFdpb0thcHI5T2NBS1A4V0VSTGhRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM0OTA2MzAyNjg4NzoxOUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJWZDB0bFBZdFQ0N1JLemxwZCtjdk1UMDJxYW9aRGdDTXViaGpVd2d2VTVYIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQWdJQlE9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NDAyNDAwMjAsImxhc3RQcm9wSGFzaCI6Im5tM0JiIn0=",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
